version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./be/.env
    volumes:
      - chroma_db:/app/chroma_db_agent
      - doc_store:/app/doc_store_agent

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      BE_URL: http://backend:8000
    depends_on:
      - backend

volumes:
  chroma_db:
  doc_store:
