FROM node:18-alpine  AS builder

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./


RUN pnpm install

COPY . .

RUN pnpm build

FROM node:18-alpine AS runner

WORKDIR /app


RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static


USER nextjs


EXPOSE 3000

ENV PORT=3000

CMD ["node", "server.js"]