
FROM python:3.11-slim

RUN pip install uv


WORKDIR /app


COPY pyproject.toml uv.lock* ./

RUN uv pip install --system .


COPY ./app /app/app

EXPOSE 8000


CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
